### ISSUE TITLE
No meeting notes for (2014 and) 2016?

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/committeemeetingnotes#1]

**Comment by verwinv** [comment]
Hi Reto, meeting notes in Gdoc form can be found here:
https://drive.google.com/open?id=1n9GfQ7HHyK6kwtyP7Gh--LV8Of4zFnhkvGwQFndPcGo

Made at attempt at converting them automagically (using the gcdocs2md script) and posted it here: 
 https://github.com/amiaopensource/committeemeetingnotes/wiki/committee-meeting-notes,-11-10-2016-Pittsburgh,-PA - doesn't seem to play nice with the tables etc. in the source document though. 

As for 2014, I was not present, nor am I aware of notes from that time.

**Comment by retokromer** [comment]
Hello Erwin, the link to google could be published here. (I’ll do it as soon as I’ll have again a regular keyboard.)

**Comment by verwinv** [comment]
Fixed it! For further questions about 2014 I'd defer to @dericed or Jack.

**Comment by retokromer** [comment]
Thank you, Erwin!

**Comment by retokromer** [comment]
I modified the dates in the titles to RFC 3339 format. This way is chronological :-)
